// Token export (Workstream B) — HEX/RGB only; never the labelled CMYK-approx or Pantone-nearest
// (those stay on-screen display). Five formats: Tailwind v4 @theme, W3C design tokens, Figma
// variables JSON, plain CSS custom properties, and binary Adobe Swatch Exchange (ASEF).
import { hexToRgb } from './color.js';

export function slugName(name) { return (name || 'palette').toLowerCase().replace(/[^a-z0-9]+/g, '-').replace(/^-+|-+$/g, '') || 'palette'; }

export function primitiveEntries(pal) {
  const slug = slugName(pal.name);
  return pal.swatches.slice().sort((a, b) => b.weight - a.weight).map((s, i) => {
    const n = String(i + 1).padStart(2, '0');
    return { key: n, cssName: 'palette-' + slug + '-' + n, hex: s.hex.toUpperCase(), rgb: hexToRgb(s.hex) };
  });
}

// Role-mapped scaffold from lightness + chroma — a starting point to refine, NOT a finished system.
export function semanticRoles(pal) {
  const sw = pal.swatches.map((s) => ({ hex: s.hex.toUpperCase(), L: s.L, C: Math.sqrt(s.a * s.a + s.b * s.b) }));
  const byL = sw.slice().sort((a, b) => b.L - a.L), byC = sw.slice().sort((a, b) => b.C - a.C), n = byL.length;
  return [
    { role: 'surface', hex: byL[0].hex },
    { role: 'surface-raised', hex: (byL[1] || byL[0]).hex },
    { role: 'on-surface', hex: byL[n - 1].hex },
    { role: 'on-surface-muted', hex: (byL[n - 2] || byL[n - 1]).hex },
    { role: 'accent', hex: byC[0].hex },
  ];
}
export function semanticEntries(pal) {
  const slug = slugName(pal.name);
  return semanticRoles(pal).map((r) => ({ key: r.role, cssName: 'palette-' + slug + '-' + r.role, hex: r.hex.toUpperCase(), rgb: hexToRgb(r.hex) }));
}

export function buildTailwind(pal, entries, semantic) {
  let out = '/* ' + pal.name + ' — Tailwind v4 @theme' + (semantic ? ' (semantic scaffold — refine before shipping)' : ' (primitive palette)') + '. HEX only. */\n@theme {\n';
  entries.forEach((e) => { out += '  --color-' + e.cssName + ': ' + e.hex + ';\n'; });
  return out + '}\n';
}
export function buildCssFile(pal, entries, semantic) {
  let out = '/* ' + pal.name + (semantic ? ' — semantic scaffold (refine before shipping)' : ' — primitive palette') + '. HEX only. */\n:root {\n';
  entries.forEach((e) => { out += '  --' + e.cssName + ': ' + e.hex + ';\n'; });
  return out + '}\n';
}
export function buildW3CTokens(pal, entries, semantic) {
  const group = { '$type': 'color' };
  if (semantic) group['$description'] = 'Semantic scaffold: a role-mapped starting point to refine, not a finished system.';
  entries.forEach((e) => { group[e.key] = { '$value': e.hex, '$type': 'color' }; });
  const obj = {}; obj[slugName(pal.name)] = group;
  return JSON.stringify(obj, null, 2) + '\n';
}
export function buildFigmaTokens(pal, entries) {
  const group = {};
  entries.forEach((e) => { group[e.key] = { value: e.hex, type: 'color' }; });
  const obj = {}; obj[slugName(pal.name)] = group;
  return JSON.stringify(obj, null, 2) + '\n';
}
// Adobe Swatch Exchange (ASEF) — RGB float entries.
export function buildASE(entries) {
  const blocks = entries.map((e) => {
    const name = e.cssName, nameLen = name.length + 1;
    const body = new ArrayBuffer(2 + nameLen * 2 + 4 + 12 + 2); const dv = new DataView(body); let o = 0;
    dv.setUint16(o, nameLen); o += 2;
    for (let i = 0; i < name.length; i++) { dv.setUint16(o, name.charCodeAt(i)); o += 2; }
    dv.setUint16(o, 0); o += 2;
    [0x52, 0x47, 0x42, 0x20].forEach((b) => { dv.setUint8(o, b); o += 1; });   // 'RGB '
    dv.setFloat32(o, e.rgb[0] / 255); o += 4; dv.setFloat32(o, e.rgb[1] / 255); o += 4; dv.setFloat32(o, e.rgb[2] / 255); o += 4;
    dv.setUint16(o, 0x0002); o += 2;   // colour type: normal
    return body;
  });
  let total = 12; blocks.forEach((b) => { total += 6 + b.byteLength; });
  const out = new ArrayBuffer(total); const dv = new DataView(out); let o = 0;
  [0x41, 0x53, 0x45, 0x46].forEach((b) => { dv.setUint8(o, b); o += 1; });   // 'ASEF'
  dv.setUint16(o, 1); o += 2; dv.setUint16(o, 0); o += 2; dv.setUint32(o, blocks.length); o += 4;
  blocks.forEach((b) => { dv.setUint16(o, 0x0001); o += 2; dv.setUint32(o, b.byteLength); o += 4; new Uint8Array(out, o, b.byteLength).set(new Uint8Array(b)); o += b.byteLength; });
  return new Blob([out], { type: 'application/octet-stream' });
}

export function paletteHexList(pal) { return pal.swatches.map((s) => s.hex.toUpperCase()).join('\n'); }
export function paletteCss(pal) {
  const slug = slugName(pal.name);
  let out = '/* ' + pal.name + ' — generated by Palette */\n:root {\n';
  pal.swatches.forEach((s, i) => { out += '  --' + slug + '-' + (i + 1) + ': ' + s.hex.toUpperCase() + ';\n'; });
  return out + '}\n';
}
