/* WHERE EACH COLOUR LIVES — the picture, classified back onto its own palette.

   The mobile story asks a question the archive never had to answer: not "what are the five colours",
   which extraction already returns, but "which parts of the photograph produced THIS one". The
   product brief proposes shipping a precomputed mask texture per colour per case. That would be five
   more assets for every example, generated by a step outside the build, kept in sync with a palette
   by hand — and the palettes are seeded from measured swatches that already carry their own OKLab
   coordinates. The masks are derivable from what is already here, so they are derived.

   ONE INDEX MAP, NOT FIVE TEXTURES. Every per-swatch mask is a view of the same fact: for each
   pixel, which swatch is nearest. That is one byte per pixel — five colours, so a byte is generous —
   and the five masks fall out of it by comparison. Storing five alpha planes instead would be five
   times the memory to say the same thing, and would let them disagree.

   THE METRIC IS THE EXTRACTOR'S OWN. Nearest is measured with dist2() in OKLab against the swatch's
   stored {L,a,b}, which is the metric kmeans() clusters with in color.js. That is what makes the
   highlight honest: the mask cannot claim a region for a colour the extractor would have assigned
   elsewhere, because it is asking the same question with the same ruler. A second opinion computed
   in sRGB or HSL would drift from the palette it is illustrating, and the drift would be worst
   exactly where it shows most — the boundaries between two close colours.

   RESOLUTION IS A LEGIBILITY QUESTION, NOT A FIDELITY ONE. A mask says WHERE, at the scale of a
   region a thumb can point at; it is never asked to resolve an edge. MAX_EDGE caps the long side at
   256, so the whole classification is ~50k pixels against five centroids — a couple of hundred
   thousand distance comparisons, low single-digit milliseconds on a phone, done once per case and
   cached. Scaled back up to a 375pt screen the browser's own smoothing feathers the boundary, which
   is the soft edge the effect wants anyway; a mask computed at full resolution would cost twenty
   times as much to produce a harder edge we would then have to blur.

   EVERY FAILURE RETURNS null. A tainted canvas, a decode that never finished, a palette with no
   usable coordinates: the caller's contract is that a missing mask means the chapter shows the
   photograph unhighlighted, which is a quieter version of the same screen rather than a broken one.
   Nothing here throws into a scroll handler. */

import { dist2, rgb2oklab } from './color.js';

/* The long edge, in pixels, the classification runs at. See the note above: this is chosen for what
   a region needs to be readable, not for what an edge needs to be sharp. */
const MAX_EDGE = 256;

/* Below this share of the frame a swatch has no region worth pointing at — it is scattered
   highlights, sensor noise, or the dark line between two things. The chapter uses this to decide
   whether a swatch can be asked "where does this live"; a mask that lights up four hundred
   disconnected pixels answers the question with a lie. Expressed against the classified pixel
   count, so it is independent of MAX_EDGE. */
const MIN_COVERAGE = 0.012;

/* AND A SECOND GATE, FOR WHEN TWO SWATCHES ARE THE SAME COLOUR TWICE.

   Measured on the eight seeded examples: seven of them classify to within 2.4 points of the
   palette's own weights, and most to within one. Frozen Slate does not. Its `#000000` is stated at
   20.8% and measures 6.5; its `#090606` is stated at 9.0 and measures 23.6. The two have swapped,
   and they swapped because they are 0.127 apart in OKLab — the same black, twice. k-means split
   those pixels by the history of how its clusters moved; a fresh nearest-centroid pass splits them
   by pure proximity, and between two centroids that close the boundary is arbitrary.

   NEITHER MASK IS WRONG ABOUT WHERE THE DARK IS. Both are wrong about which of the two owns it, and
   that is the claim the chapter would be making — it puts a swatch labelled 21% next to a region
   covering 7% of the frame, and the reader is right to believe the picture over the label.

   Distance alone does not predict this: Frozen Slate's two BLUES are 0.121 apart, closer than the
   blacks, and they classify almost perfectly (34.8 vs 34.9, 33.8 vs 33.6) because they occupy
   genuinely separate parts of the frame. So the test is the disagreement itself, not the geometry
   that might cause it — measure the drift and refuse the ones that fail.

   Refused rather than merged. Merging the pair into one shared mask would show the true dark region
   and is tempting, but it makes two different swatches highlight the same area, which reads as a
   broken control rather than as an honest one. A swatch with no region simply is not offered — the
   same graceful path MIN_COVERAGE already takes, for a second reason. */
const MAX_DRIFT = 0.05;

function decodedSize(img) {
  const w = img.naturalWidth || img.width || 0;
  const h = img.naturalHeight || img.height || 0;
  return (w > 0 && h > 0) ? [w, h] : null;
}

/* The palette as centroids this module can compare against.

   Seeds carry L/a/b already — seedObj() computes them at build time from the hex — but a palette
   that arrived down a share link or out of a refinement may not, and a swatch whose coordinates are
   missing must not silently classify every pixel to itself at distance zero. So each entry is either
   validated or recomputed from its hex, and a swatch that can produce neither drops out of the
   comparison entirely rather than poisoning it. */
function centroids(swatches) {
  if (!Array.isArray(swatches) || !swatches.length) return null;
  const out = [];
  for (let i = 0; i < swatches.length; i++) {
    const s = swatches[i];
    if (!s) continue;
    let L = s.L, a = s.a, b = s.b;
    if (!isFinite(L) || !isFinite(a) || !isFinite(b)) {
      const hex = typeof s.hex === 'string' ? s.hex.replace('#', '') : '';
      if (!/^[0-9a-f]{6}$/i.test(hex)) continue;
      const lab = rgb2oklab(
        parseInt(hex.slice(0, 2), 16) / 255,
        parseInt(hex.slice(2, 4), 16) / 255,
        parseInt(hex.slice(4, 6), 16) / 255,
      );
      L = lab.L; a = lab.a; b = lab.b;
    }
    out.push({ sid: i, L, a, b });
  }
  return out.length ? out : null;
}

/* Classify every pixel of `img` to its nearest swatch.

   Returns {w, h, idx, coverage} — `idx` is one byte per pixel holding the swatch index, and
   `coverage` is the measured share of the frame each swatch actually occupies.

   COVERAGE IS NOT `weight`, AND THE DIFFERENCE IS THE POINT. A swatch's stored weight is the share
   of the CLUSTER the extractor built, taken from a downsampled read of the image at generation time.
   This is the share of the frame at this resolution, measured now. They agree closely and they are
   not the same number, so the story quotes `weight` wherever it states a percentage — that figure is
   the palette's own, and it is what the desktop shows — and uses coverage only to decide whether a
   swatch HAS a region worth pointing at. Quoting one number in the text and another in the picture
   is how a reading stops being trustworthy. */
export function buildIndexMap(img, swatches) {
  try {
    const size = decodedSize(img);
    const cents = centroids(swatches);
    if (!size || !cents) return null;

    const scale = Math.min(1, MAX_EDGE / Math.max(size[0], size[1]));
    const w = Math.max(1, Math.round(size[0] * scale));
    const h = Math.max(1, Math.round(size[1] * scale));

    const cv = document.createElement('canvas');
    cv.width = w; cv.height = h;
    const ctx = cv.getContext('2d', { willReadFrequently: true });
    if (!ctx) return null;
    ctx.drawImage(img, 0, 0, w, h);

    // Throws a SecurityError on a tainted canvas. The example images are bundled and same-origin, so
    // this is the guard for a future case served from elsewhere rather than a live failure.
    const data = ctx.getImageData(0, 0, w, h).data;

    const n = w * h;
    const idx = new Uint8Array(n);
    const counts = new Uint32Array(swatches.length);
    // Reused across the loop: one object rather than n of them, because this is the only place in
    // the story that allocates per pixel and a 50k-object garbage run on a phone is a visible hitch.
    const px = { L: 0, a: 0, b: 0 };

    for (let i = 0, p = 0; i < n; i++, p += 4) {
      const lab = rgb2oklab(data[p] / 255, data[p + 1] / 255, data[p + 2] / 255);
      px.L = lab.L; px.a = lab.a; px.b = lab.b;
      let best = cents[0].sid, bestD = dist2(px, cents[0]);
      for (let c = 1; c < cents.length; c++) {
        const d = dist2(px, cents[c]);
        if (d < bestD) { bestD = d; best = cents[c].sid; }
      }
      idx[i] = best;
      counts[best]++;
    }

    const coverage = [];
    for (let s = 0; s < swatches.length; s++) coverage.push(counts[s] / n);

    return { w, h, idx, coverage };
  } catch (e) { return null; }
}

/* Does this swatch own a region the chapter can honestly point at?

   Two independent reasons it may not: too little of the frame to be a region at all (MIN_COVERAGE),
   or a classification that disagrees with the palette's own weight badly enough that the picture
   would contradict the label (MAX_DRIFT). `swatches` is optional — without it only the first test
   runs, which is the right answer for a caller that has no weights to compare against. */
export function hasRegion(map, sid, swatches) {
  if (!map || !map.coverage) return false;
  const cov = map.coverage[sid];
  if (!(cov >= MIN_COVERAGE)) return false;
  const s = swatches && swatches[sid];
  if (s && isFinite(s.weight)) {
    const total = swatches.reduce((a, x) => a + ((x && isFinite(x.weight)) ? x.weight : 0), 0);
    if (total > 0 && Math.abs(cov - (s.weight / total)) > MAX_DRIFT) return false;
  }
  return true;
}

/* One swatch's mask, as an alpha PNG data URL.

   OPAQUE WHERE THE SWATCH LIVES, TRANSPARENT EVERYWHERE ELSE — which is what CSS mask-image and a
   WebGL alpha texture both want, so one product serves the DOM path and the canvas path rather than
   each growing its own.

   The RGB channels are left white rather than black. An alpha-only PNG is legal and smaller, but a
   mask used as a plain <img> or drawn with a composite operation somewhere later would then paint
   black fringes wherever the alpha is partial; white fringes are invisible against every surface
   this site has. Costs nothing, removes a whole class of future surprise. */
export function maskDataUrl(map, sid) {
  try {
    if (!map || !map.idx) return null;
    const { w, h, idx } = map;
    const cv = document.createElement('canvas');
    cv.width = w; cv.height = h;
    const ctx = cv.getContext('2d');
    if (!ctx) return null;
    const out = ctx.createImageData(w, h);
    const d = out.data;
    for (let i = 0, p = 0; i < idx.length; i++, p += 4) {
      d[p] = 255; d[p + 1] = 255; d[p + 2] = 255;
      d[p + 3] = idx[i] === sid ? 255 : 0;
    }
    ctx.putImageData(out, 0, 0);

    /* AND A FEATHERED EDGE, because the boundary is a decision and not a fact.

       The mask is computed at 256px and displayed across ~390pt, and the first version of this
       function returned it hard-edged on the assumption that the browser's own scaling would soften
       it. It does not: rendered as a CSS mask the boundary comes back visibly stair-stepped, and on
       screen it reads as a low-resolution image rather than as a region of a photograph.

       It should be soft for a truer reason than tidiness, though. Every pixel on that boundary is a
       near-tie between two centroids — the point where "this belongs to the terracotta" becomes
       "this belongs to the shadow" — and a hard line claims a precision the classification does not
       have. A feathered edge is the honest rendering of a soft decision.

       One blur, applied by drawing the canvas through itself. 1.5px at 256 is a little under half a
       percent of the frame: enough to kill the stepping, far too little to move where a region is.
       ctx.filter is unsupported in older Safari, where this is a no-op and the mask simply stays
       hard — a worse edge, not a broken one, which is the right way for this to fail. */
    try {
      const soft = document.createElement('canvas');
      soft.width = w; soft.height = h;
      const sctx = soft.getContext('2d');
      if (sctx && 'filter' in sctx) {
        sctx.filter = 'blur(1.5px)';
        sctx.drawImage(cv, 0, 0);
        return soft.toDataURL('image/png');
      }
    } catch (e) { }

    return cv.toDataURL('image/png');
  } catch (e) { return null; }
}

/* Every mask for a palette, built once.

   Returns {map, urls} where urls[i] is null for any swatch with no region worth showing — the caller
   tests the entry rather than re-deriving the threshold, so MIN_COVERAGE is applied in exactly one
   place. Null overall if the classification itself failed, which is the caller's cue to show the
   photograph plain. */
export function buildMasks(img, swatches) {
  const map = buildIndexMap(img, swatches);
  if (!map) return null;
  const urls = [];
  for (let s = 0; s < swatches.length; s++) urls.push(hasRegion(map, s, swatches) ? maskDataUrl(map, s) : null);
  return { map, urls };
}
